name: CI/CD for Pallets Website
on:
  push:
    branches: [ github-action ]
  pull_request:
    branches: [ master ]

jobs: 
  setup-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

  setup-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
  build:
    runs-on: ubuntu-latest

    # Installation, Build and Deployment
    steps:
      - name: Fix GitHub Actions path
        run: echo /home/runner/.local/bin >>$GITHUB_PATH

      - name: Install Lektor, Node dependencies
        run:
          pip install lektor
          npm install
      
      - name: Build
        run:
          lektor build -f webpack   # Build

      - name: Deploy
        run: 
          lektor deploy production   # Deploy

      # Webhook

      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v1.0.5
        with:
          url: https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
