name: CI/CD for Pallets Website
on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Installations and Deployment

      - name: Install Lektor and Node dependensies
        run: 
          pip install lektor
          npm install --global npm@latest
      - name: Build
        run: 
          lektor build -f webpack   # Build
      - name: Deploy
        run: 
          lektor deploy production   # Deploy

      # Webhook

      - name: Webhook
        uses: distributhor/workflow-webhook
        with:
          url: https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
